package com.example.myfooddelivery.constants

enum class Screens {
    HOME_SCREEN, ORDER_SCREEN, PROFILE_SCREEN,
    NEW_ORDER_SCREEN, PROFILE_UPDATE_SCREEN,
    VIEW_PARTICULAR_ORDER_SCREEN,
    ORDER_SUMMARY_SCREEN,
    SEARCH_SCREEN,
    FAVORITES_SCREEN,
    ORDER_DISPATCHED_SCREEN
}